'use client';
import {useGame} from '../state/game-store';
import {Modal} from './Modal';
import {Field} from './primitives';
export function Settings({onClose}:{onClose:()=>void}){const {preferences:p,setPreferences}=useGame();return <Modal title="Make yourself comfortable." subtitle="Your preferences are saved on this device." onClose={onClose}>
  <div className="two-col"><Field>Game pace<select value={p.speed} onChange={e=>setPreferences({speed:e.target.value as typeof p.speed})}>{['Slow','Normal','Fast','Instant'].map(s=><option key={s}>{s}</option>)}</select></Field><Field>Camera<select value={p.camera} onChange={e=>setPreferences({camera:e.target.value as typeof p.camera})}><option value="player">Player perspective</option><option value="overhead">Overhead</option></select></Field></div>
  {([['sound','Table sounds','Soft card, chip and action sounds.'],['helper','Hand-strength helper','Name your made hand and highlight your best five cards.'],['potOdds','Pot odds','See the equity needed to call.'],['winOdds','Win odds','Estimated chance to win and improve, updated each street.'],['hints','Table hints','Tips based on your odds and the price of a call.'],['autoMuck','Automatic mucking','Keep uncontested winning cards private.'],['reducedMotion','Reduced motion','Skip dealing motion and camera effects.']] as const).map(([key,title,description])=><label className="settings-row" key={key}><span>{title}<small>{description}</small></span><input type="checkbox" checked={p[key]} onChange={e=>setPreferences({[key]:e.target.checked})}/></label>)}
  </Modal>;}
export function Help({onClose}:{onClose:()=>void}){return <Modal title="A good hand starts here." subtitle="No-limit Texas Hold’em, at your own pace." onClose={onClose}><ol><li>You receive two private cards. Make your best five-card hand using any combination of your cards and the five community cards.</li><li>Call to match a bet, raise to increase it, or fold to leave the hand. With no bet to match, you can check or bet.</li><li>The flop brings three cards, then the turn and river bring one each. Each street has a betting round.</li><li>The best remaining hand wins. All-in players can only win the pots their contributions cover.</li></ol><p><span className="help-key">F</span> Fold &nbsp; <span className="help-key">C</span> Check / call &nbsp; <span className="help-key">R</span> Bet / raise &nbsp; <span className="help-key">A</span> All-in</p><div className="rules"><p>Strongest to weakest: royal flush, straight flush, four of a kind, full house, flush, straight, three of a kind, two pair, one pair, high card.</p><p style={{marginTop:12}}>Ties split the pot. Odd chips go clockwise from the dealer. The button moves to the next occupied seat; heads-up, the dealer posts the small blind and acts first before the flop.</p></div></Modal>;}
