import {test,expect,type Page} from '@playwright/test';
async function setup(page:Page,players='6',speed='Fast'){
  await page.goto('/holdem');await page.getByRole('button',{name:'Take a seat',exact:true}).click();await page.getByLabel('Players, including you').selectOption(players);await page.getByLabel('Game pace').selectOption(speed);await page.getByRole('dialog').getByRole('button',{name:'Take a seat',exact:true}).click();await expect(page.locator('.hand-number')).toHaveText('HAND 001');await expect(page.locator('[data-render-ready=true]')).toHaveCount(1,{timeout:40000});
}
test('desktop: setup, 3D, live AI, controls, history, pause, settings and refresh',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await setup(page);await expect(page.locator('canvas')).toBeVisible();await expect(page.locator('.seat')).toHaveCount(6);await expect(page.locator('.turn-note')).toBeVisible({timeout:40000});await expect(page.locator('.hole-cards .playing-card[aria-label]')).toHaveCount(2);await expect(page.locator('.board-strip .playing-card, .board-strip .card-slot')).toHaveCount(5);await expect(page.locator('.odds-figures')).toContainText(/Win \d+%/,{timeout:15000});await expect(page.locator('.tip')).toBeVisible();await page.screenshot({path:'artifacts/desktop.png',fullPage:true});
  const actions=page.locator('.action-buttons');const call=actions.getByRole('button',{name:/Call |Check/});await call.click();await expect(page.locator('.error-bar')).toHaveCount(0);await page.getByRole('button',{name:'Pause game',exact:true}).click();await expect(page.getByText('TABLE PAUSED',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Hand history',exact:true}).click();await expect(page.getByRole('complementary',{name:'Hand history'})).toContainText('Hand #1');await page.getByRole('button',{name:'Close history'}).click();
  await page.getByRole('button',{name:'Open settings'}).click();await page.getByLabel('Reduced motion').check();await page.getByLabel('Game pace').selectOption('Slow');await page.getByRole('button',{name:'Close dialog'}).click();await page.reload();await expect(page.getByRole('button',{name:'Take a seat',exact:true})).toBeVisible();await page.getByRole('button',{name:'Open settings'}).click();await expect(page.getByLabel('Reduced motion')).toBeChecked();await expect(page.getByLabel('Game pace')).toHaveValue('Slow');expect(errors).toEqual([]);
});
test('development tools reproduce side pots and a correct showdown',async({page})=>{
  await setup(page,'3','Slow');await page.getByRole('button',{name:'Developer tools'}).click();await page.getByRole('button',{name:'Force 3-way all-in'}).click();await page.getByRole('button',{name:'Run to showdown'}).click();await page.getByText('Complete engine state & deck').click();const state=JSON.parse(await page.locator('dialog pre').innerText());expect(state.phase).toBe('SHOWDOWN');expect(state.sidePots.map((p:{amount:number})=>p.amount)).toEqual([900,1200]);expect(state.players.reduce((n:number,p:{stack:number})=>n+p.stack,0)).toBe(3700);expect(Object.keys(state.results)).toHaveLength(3);await page.getByRole('button',{name:'Close dialog'}).click();await page.screenshot({path:'artifacts/showdown.png',fullPage:true});await expect(page.locator('.result-banner')).toBeVisible();
});
test('mobile: nine seats, readable hand, legal action, no horizontal overflow',async({page})=>{
  await page.setViewportSize({width:390,height:844});await setup(page,'9');await expect(page.locator('.seat')).toHaveCount(9);await expect(page.locator('.turn-note')).toBeVisible({timeout:45000});await page.screenshot({path:'artifacts/mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await expect(page.locator('.action-buttons')).toBeVisible();await page.locator('.action-buttons').getByRole('button',{name:/Call |Check/}).click();await expect(page.locator('.error-bar')).toHaveCount(0);
});
test('heads-up: human small blind starts and can raise with keyboard',async({page})=>{
  await setup(page,'2','Slow');await expect(page.locator('.turn-note')).toBeVisible();const input=page.getByRole('spinbutton',{name:'Bet or raise amount'});await expect(input).toHaveValue('100');await input.fill('150');await input.blur();await page.keyboard.press('r');await page.getByRole('button',{name:'Hand history',exact:true}).click();await expect(page.locator('.history-list')).toContainText('You · Raise to 150');await expect(page.locator('.error-bar')).toHaveCount(0);
});
