'use client';
import {useEffect,useState,type CSSProperties} from 'react';
import {total,canDouble,canSplit} from '../../games/blackjack';
import {useBlackjack} from '../../state/blackjack-store';
import {Button} from '../primitives';
import {Card} from './Card';
import {ClubShell,useCardSound} from './ClubShell';
const chips=(value:number)=>value.toLocaleString('en-US',{maximumFractionDigits:1});
export default function Blackjack() {
  const {game:g,act}=useBlackjack(),[bet,setBet]=useState(25),sound=useCardSound();
  const choosing=g.phase==='betting'||g.phase==='settled',playing=g.phase==='player',revealed=g.phase==='dealer'||g.phase==='settled';
  const wager=Math.min(bet,Math.floor(g.bank/5)*5),profit=g.hands.reduce((sum,h)=>sum+(h.returned??0)-h.bet,0);
  useEffect(()=>{if(g.phase!=='dealing'&&g.phase!=='dealer')return;const id=setTimeout(()=>act({type:g.phase==='dealing'?'ready':'dealer'}),g.phase==='dealing'?1100:750);return()=>clearTimeout(id);},[g,act]);
  function action(type:'hit'|'stand'|'double'|'split'){sound.play();act({type});}
  const visibleDealer=revealed?total(g.dealer).value:g.dealer.length?total(g.dealer.slice(0,1)).value:0;
  return <ClubShell title="Blackjack" sound={sound} rules={<><p>Six decks. Blackjack pays 3:2. The dealer stands on all 17s, including soft 17. A tie returns your wager.</p><ol><li>Choose your wager and deal. Get closer to 21 than the dealer without going over.</li><li>Hit for another card, or stand. Aces count as 1 or 11.</li><li>Double on your first two cards: double the wager and receive one final card. You may double after splitting.</li><li>Split equal-value cards into two hands, once per round. Split aces receive one card each. A split 21 pays 1:1.</li></ol><p>Play chips only. No insurance or surrender. Your table stays here when you return through the menu.</p></>}>
    <main className="blackjack-room"><div className="bj-balance"><span>CHIPS</span><strong>{chips(g.bank)}</strong></div><div className="bj-table">
      <div className="bj-rail"/><div className="bj-shoe" aria-hidden="true"><Card card="As" down/></div>
      <section className="dealer-hand" aria-label="Dealer hand"><div className="hand-caption">DEALER {visibleDealer>0&&<b key={visibleDealer}>{visibleDealer}{!revealed?' + ?':''}</b>}</div><div className="bj-cards" style={{'--hand-size':g.dealer.length} as CSSProperties}>{g.dealer.map((card,i)=><div className="bj-card-deal" key={`${g.round}-dealer-${i}`} style={{'--deal-delay':`${g.phase==='dealing'?(i*2+1)*180:0}ms`,'--tilt':`${i%2?3:-3}deg`} as CSSProperties}><Card card={card} down={i===1&&!revealed}/></div>)}{!g.dealer.length&&<><span className="bj-empty-card"/><span className="bj-empty-card"/></>}</div></section>
      <div className="bj-center" aria-live="polite" aria-atomic="true">{g.phase==='settled'?<div className={`bj-outcome ${profit>0?'outcome-win':''}`} key={g.round}><strong>{g.hands.length===1?g.hands[0].result:profit>0?'You win':profit<0?'Dealer wins':'Push'}</strong><span>{profit>0?'+':''}{chips(profit)} chips</span></div>:<div className="felt-inscription"><span>BLACKJACK PAYS 3 TO 2</span><small>DEALER STANDS ON 17</small></div>}</div>
      <div className={`player-hands ${g.hands.length>1?'split-hands':''}`}>{g.hands.length?g.hands.map((hand,hi)=><section className={`player-hand ${playing&&g.active===hi?'active-hand':''}`} key={`${g.round}-${hi}`} aria-label={`Your hand${g.hands.length>1?` ${hi+1}`:''}`}><div className="bj-cards" style={{'--hand-size':hand.cards.length} as CSSProperties}>{hand.cards.map((card,i)=><div className="bj-card-deal" key={`${g.round}-${hi}-${i}`} style={{'--deal-delay':`${g.phase==='dealing'?i*360:0}ms`,'--tilt':`${i%2?2:-2}deg`} as CSSProperties}><Card card={card}/></div>)}</div><div className="hand-caption">{g.hands.length>1?`HAND ${hi+1}`:'YOU'}<b key={total(hand.cards).value}>{total(hand.cards).value}{total(hand.cards).soft?' / soft':''}</b>{g.phase==='settled'&&<span>{hand.result}</span>}</div><span className="wager-chip">{chips(hand.bet)}</span></section>):<div className="player-hand idle-hand"><div className="bj-cards"><span className="bj-empty-card"/><span className="bj-empty-card"/></div><span className="wager-chip">{chips(wager)}</span></div>}</div>
    </div><div className="bj-controls">{choosing?<>{g.bank>=10?<><div className="bet-selector" aria-label="Wager">{[10,25,50,100].map(n=><button key={n} className={`bet-chip ${bet===n?'selected':''}`} aria-label={`Bet ${n} chips`} aria-pressed={bet===n} disabled={n>g.bank} onClick={()=>{setBet(n);sound.play();}}>{n}</button>)}</div><Button $primary onClick={()=>{sound.play();act({type:'deal',bet:wager,seed:crypto.getRandomValues(new Uint32Array(1))[0]});}}>Deal · {chips(wager)}</Button></>:<Button $primary onClick={()=>act({type:'refill'})}>Refill 1,000 play chips</Button>}</>:<div className="bj-action-buttons"><Button $primary disabled={!playing} onClick={()=>action('hit')}>Hit</Button><Button disabled={!playing} onClick={()=>action('stand')}>Stand</Button><Button disabled={!canDouble(g)} onClick={()=>action('double')}>Double</Button><Button disabled={!canSplit(g)} onClick={()=>action('split')}>Split</Button></div>}</div><div className="club-footnote">PLAY CHIPS ONLY</div></main>
  </ClubShell>;
}
