'use client';
import {useEffect,useRef,useState,type CSSProperties,type PointerEvent} from 'react';
import {ArrowCounterClockwiseIcon,LightbulbIcon,ArrowsClockwiseIcon,MagicWandIcon} from '@phosphor-icons/react';
import {cardLabel,newDeck,SUIT_SYMBOLS} from '../../game/cards';
import type {Card as CardValue} from '../../game/types';
import {canMove,drawCard,isWon,legalMoves,moveCards,pileCards,safeFoundationMove,type Pile,type Source} from '../../games/solitaire';
import {useSolitaire} from '../../state/solitaire-store';
import {Button,IconButton} from '../primitives';
import {Modal} from '../Modal';
import {Card} from './Card';
import {ClubShell,useCardSound} from './ClubShell';
type Position={col:number;row:number;depth:number;z:number;down:boolean;source?:Source;visible:boolean};
const pileKey=(p:Pile)=>p.type==='waste'?'waste':`${p.type}-${p.index}`;
function parsePile(key:string):Pile|null{if(key==='waste')return {type:'waste'};const [type,i]=key.split('-');return (type==='foundation'||type==='tableau')&&/^\d$/.test(i)?{type,index:Number(i)}:null;}
export default function Solitaire(){
  const {game:g,history,deal,set,fresh,undo}=useSolitaire(),sound=useCardSound();
  const [selected,select]=useState<Source|null>(null),[hint,setHint]=useState<{from:Source;to:Pile}|null>(null),[message,setMessage]=useState(''),[confirm,setConfirm]=useState(false),[auto,setAuto]=useState(false);
  const drag=useRef<{source:Source;x:number;y:number;ids:CardValue[];moved:boolean}|null>(null),board=useRef<HTMLDivElement>(null),suppress=useRef(false);
  useEffect(()=>{if(!useSolitaire.getState().game)fresh();},[fresh]);
  useEffect(()=>{if(!auto||!g)return;const move=safeFoundationMove(g);if(!move){setAuto(false);return;}const timer=setTimeout(()=>set(moveCards(g,move.from,move.to)),160);return()=>clearTimeout(timer);},[auto,g,set]);
  useEffect(()=>{function keys(e:KeyboardEvent){if(e.target instanceof HTMLElement&&e.target.closest('dialog,input,select'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo();select(null);setHint(null);setAuto(false);}if(e.key==='Escape'){select(null);setHint(null);setAuto(false);}}window.addEventListener('keydown',keys);return()=>window.removeEventListener('keydown',keys);},[undo]);
  if(!g)return <div className="club-shell" role="status">Dealing…</div>;
  const won=isWon(g),positions=new Map<CardValue,Position>();
  g.stock.forEach((card,i)=>positions.set(card,{col:0,row:0,depth:0,z:i,down:true,visible:i===g.stock.length-1}));
  g.waste.forEach((card,i)=>positions.set(card,{col:1,row:0,depth:0,z:i,down:false,source:{type:'waste',offset:i},visible:i===g.waste.length-1}));
  g.foundations.forEach((cards,index)=>cards.forEach((card,i)=>positions.set(card,{col:index+3,row:0,depth:0,z:i,down:false,source:{type:'foundation',index,offset:i},visible:i===cards.length-1})));
  g.tableau.forEach((cards,index)=>{let depth=0;cards.forEach((card,i)=>{const down=!g.faceUp.includes(card);positions.set(card,{col:index,row:1,depth,z:i,down,source:{type:'tableau',index,offset:i},visible:true});depth+=down?.48:1;});});
  const maxDepth=Math.max(5,...[...positions.values()].filter(p=>p.row===1).map(p=>p.depth));
  function clear(){select(null);setHint(null);setMessage('');setAuto(false);}
  function move(from:Source,to:Pile){if(!g)return false;if(canMove(g,from,to)){set(moveCards(g,from,to));clear();sound.play();return true;}setMessage('That card cannot go there.');return false;}
  function choose(source:Source){if(!g||auto)return;if(selected&&pileKey(selected)===pileKey(source)&&selected.offset===source.offset){clear();return;}if(selected&&move(selected,source)){return;}select(source);setHint(null);setMessage(`${cardLabel(pileCards(g,source)[source.offset])} selected`);}
  function target(pile:Pile){if(selected)move(selected,pile);}
  function toFoundation(source:Source){if(!g)return;const index=g.foundations.findIndex((_,index)=>canMove(g,source,{type:'foundation',index}));if(index>=0)move(source,{type:'foundation',index});}
  function startDrag(e:PointerEvent<HTMLButtonElement>,source:Source){if(!g||auto||e.button!==0)return;drag.current={source,x:e.clientX,y:e.clientY,ids:pileCards(g,source).slice(source.offset),moved:false};e.currentTarget.setPointerCapture(e.pointerId);}
  function dragMove(e:PointerEvent<HTMLButtonElement>){const d=drag.current;if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.abs(dx)+Math.abs(dy)>6)d.moved=true;if(!d.moved)return;d.ids.forEach((id,i)=>{const el=board.current?.querySelector<HTMLElement>(`[data-card="${id}"]`);if(el){el.style.transform=`translate(${dx}px,${dy}px) rotate(2deg)`;el.style.zIndex=String(200+i);el.style.transition='none';el.style.pointerEvents='none';}});}
  function endDrag(e:PointerEvent<HTMLButtonElement>,cancel=false){const d=drag.current;if(!d)return;const destination=!cancel&&d.moved?document.elementFromPoint(e.clientX,e.clientY)?.closest<HTMLElement>('[data-pile]')?.dataset.pile:null;d.ids.forEach(id=>{const el=board.current?.querySelector<HTMLElement>(`[data-card="${id}"]`);if(el){el.style.transform='';el.style.zIndex=String(positions.get(id)?.z??0);el.style.transition='';el.style.pointerEvents='';}});drag.current=null;if(d.moved){suppress.current=true;setTimeout(()=>{suppress.current=false;},0);if(destination){const pile=parsePile(destination);if(pile)move(d.source,pile);}}}
  function getHint(){clear();const moves=legalMoves(g!);const next=moves.find(m=>m.to.type==='foundation')??moves.find(m=>m.from.type==='tableau'&&m.from.offset>0&&!g!.faceUp.includes(g!.tableau[m.from.index][m.from.offset-1]))??moves[0];if(next){setHint(next);setMessage(`Move ${cardLabel(pileCards(g!,next.from)[next.from.offset])} to ${next.to.type==='tableau'?`column ${next.to.index+1}`:'a foundation'}.`);}else setMessage(g!.stock.length?'Draw from the stock.':g!.waste.length?'Recycle the stock, or undo to try a different move.':'No suggested moves. Undo or start a new deal.');}
  return <ClubShell title="Solitaire" sound={sound} actions={<IconButton aria-label="New deal" title="New deal" onClick={()=>setConfirm(true)}><ArrowsClockwiseIcon/></IconButton>} rules={<><p>Draw-one Klondike. Build the four foundations from ace to king, by suit.</p><ol><li>Build tableau columns downward in alternating colours. Only kings can fill empty columns.</li><li>Click a face-up card, then a destination. You can also drag cards or whole sequences. Double-click a card to send it to a foundation.</li><li>Click the stock to draw one card. When empty, click it again to recycle the waste, with unlimited passes.</li><li>Undo with the button or Ctrl / ⌘ + Z. Hints highlight a legal move. Auto moves safe cards to the foundations.</li></ol><p>Every deal is shuffled; some deals cannot be won. Your game stays here when you return through the menu.</p></>}>
    <main className="solitaire-room"><div className="solitaire-stats"><span>DRAW ONE</span><span><b>{g.moves}</b> {g.moves===1?'move':'moves'} <i/> <b>{g.foundations.reduce((n,p)=>n+p.length,0)}</b> / 52</span></div>
      <div className={`solitaire-board ${won?'board-won':''}`} ref={board} style={{'--max-depth':maxDepth} as CSSProperties} aria-label="Solitaire table">
        <button className="pile-slot stock-slot" aria-label={g.stock.length?`Draw card, ${g.stock.length} remaining`:'Recycle stock'} style={{'--col':0} as CSSProperties} disabled={auto||(!g.stock.length&&!g.waste.length)} onClick={()=>{clear();set(drawCard(g));sound.play();}}><ArrowCounterClockwiseIcon size={25}/><small>{g.stock.length||''}</small></button>
        <div className="pile-slot" style={{'--col':1} as CSSProperties} aria-label="Waste"/>
        {g.foundations.map((_,index)=><button className={`pile-slot foundation-slot ${hint?.to.type==='foundation'&&hint.to.index===index?'hint-target':''}`} data-pile={`foundation-${index}`} key={`f-${index}`} style={{'--col':index+3} as CSSProperties} aria-label={`Foundation ${index+1}`} onClick={()=>target({type:'foundation',index})}>{Object.values(SUIT_SYMBOLS)[index]}</button>)}
        {g.tableau.map((_,index)=><button className={`pile-slot tableau-slot ${hint?.to.type==='tableau'&&hint.to.index===index?'hint-target':''}`} data-pile={`tableau-${index}`} key={`t-${index}`} style={{'--col':index} as CSSProperties} aria-label={`Empty column ${index+1}`} onClick={()=>target({type:'tableau',index})}><span>K</span></button>)}
        {newDeck().map(card=>{const p=positions.get(card)!;const isSelected=selected&&p.source&&pileKey(selected)===pileKey(p.source)&&p.source.offset>=selected.offset;const isHint=hint&&p.source&&pileKey(hint.from)===pileKey(p.source)&&p.source.offset===hint.from.offset;const isTarget=hint&&p.source&&pileKey(hint.to)===pileKey(p.source);return <button key={`${deal}-${card}`} className={`solitaire-card ${isSelected?'card-selected':''} ${isHint||isTarget?'card-hint':''} ${p.down?'card-down':''}`} data-card={card} data-pile={p.source?pileKey(p.source):undefined} style={{'--col':p.col,'--row':p.row,'--depth':p.depth,'--entry-delay':`${Math.min(p.z*30+p.col*35,550)}ms`,zIndex:p.z,opacity:p.visible?1:0,pointerEvents:!p.visible||(!p.source&&p.down)?'none':undefined} as CSSProperties} tabIndex={p.visible&&!p.down?0:-1} aria-hidden={!p.visible||p.down} aria-label={`${p.down?'Face-down card':cardLabel(card)}${p.source?.type==='tableau'?`, column ${p.source.index+1}`:''}`} aria-pressed={!!isSelected} onClick={()=>{if(!suppress.current&&p.source&&!p.down)choose(p.source);else if(p.down&&selected&&p.source)target(p.source);}} onDoubleClick={()=>{if(p.source&&!p.down)toFoundation(p.source);}} onPointerDown={e=>{if(p.source&&!p.down)startDrag(e,p.source);}} onPointerMove={dragMove} onPointerUp={e=>endDrag(e)} onPointerCancel={e=>endDrag(e,true)}><Card card={card} down={p.down}/></button>;})}
      </div>
      <div className="solitaire-controls"><Button $small disabled={!history.length} onClick={()=>{undo();clear();sound.play();}}><ArrowCounterClockwiseIcon size={16}/>Undo</Button><Button $small disabled={won||auto} onClick={getHint}><LightbulbIcon size={16}/>Hint</Button><Button $small disabled={won||!safeFoundationMove(g)} onClick={()=>{select(null);setHint(null);setAuto(v=>!v);}}><MagicWandIcon size={16}/>{auto?'Stop':'Auto'}</Button></div><p className="solitaire-message" role="status" aria-live="polite">{won?'':message}</p>
      {won&&<div className="solitaire-victory"><span>♠ ♥ ♣ ♦</span><strong>You win</strong><Button $primary onClick={()=>{fresh();clear();}}>New deal</Button></div>}
    </main>{confirm&&<Modal title="New deal?" subtitle="This will replace your current solitaire game." onClose={()=>setConfirm(false)}><div className="modal-footer"><Button onClick={()=>setConfirm(false)}>Keep playing</Button><Button $primary onClick={()=>{fresh();clear();setConfirm(false);}}>Deal again</Button></div></Modal>}
  </ClubShell>;
}
